version: '3.9'

services:

  api:
    container_name: trail_path_api
    hostname: trail-path-api
    image: trail-path-api
    build:
      context: .
      dockerfile: apps/api/Dockerfile
      target: development
    volumes:
      - .:/app
      - /app/node_modules
      - dist:/app/dist
    expose:
      - 3333
    labels:
      - "traefik.http.routers.api.rule=Host(`api.traefik.me`)"
      - "traefik.http.routers.api-tls.tls.domains[0].main=api.traefik.me"
      - "traefik.http.routers.api-tls.tls.domains[0].sans=api-*.traefik.me"
    command: pnpm run start:api
    healthcheck:
      test: curl -f http://localhost:3333/api/health || exit 1
      interval: 5s
      retries: 20
      start_period: 5s
      timeout: 10s
    networks:
      - trail-path-network
    restart: unless-stopped

  app:
    container_name: trail_path_app
    hostname: trail-path-app
    image: trail-path-app
    build:
      context: .
      dockerfile: apps/app/Dockerfile
      target: development
    expose:
      - 4200
    networks:
      - trail-path-network
    volumes:
      - .:/app
      - /app/node_modules
      - dist:/app/dist
    labels:
      - "traefik.http.routers.app.rule=Host(`app.traefik.me`)"
      - "traefik.http.routers.app-tls.tls.domains[0].main=app.traefik.me"
      - "traefik.http.routers.app-tls.tls.domains[0].sans=app-*.traefik.me"
    command: pnpm run start:app
    depends_on:
      api:
        condition: service_healthy
    restart: unless-stopped

  db:
    container_name: trail_path_db
    hostname: trail-path-db
    image: postgres:15.1-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
      - ./tools/db/init.sql:/docker-entrypoint-initdb.d/create_tables.sql
    networks:
      - trail-path-network
    restart: always

  pgadmin:
    image: dpage/pgadmin4
    container_name: trail_path_pgadmin
    expose:
      - 80
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@local.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION: "True"
      PGADMIN_CONFIG_CONSOLE_LOG_LEVEL: 30
      PGADMIN_CONFIG_FILE_LOG_LEVEL: 30
      GUNICORN_ACCESS_LOGFILE: /dev/null
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - trail-path-network
    labels:
      - "traefik.http.routers.pgadmin.rule=Host(`pgadmin.traefik.me`)"
    restart: unless-stopped
    depends_on:
      - db

  traefik:
    container_name: trail_path_traefik
    restart: unless-stopped
    image: traefik:latest
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    labels:
      - "traefik.http.services.traefik.loadbalancer.server.port=8080"
    volumes:
      - ./tools/traefik/traefik.yml:/etc/traefik/traefik.yml
      - ./tools/traefik/tls.yml:/etc/traefik/tls.yml
      - /var/run/docker.sock:/var/run/docker.sock
      - certs:/etc/ssl/traefik
    networks:
      - trail-path-network

  reverse-proxy-https-helper:
    container_name: trail_path_helper
    image: alpine
    command: sh -c "cd /etc/ssl/traefik
      && wget traefik.me/cert.pem -O cert.pem
      && wget traefik.me/privkey.pem -O privkey.pem"
    volumes:
      - certs:/etc/ssl/traefik

networks:
  trail-path-network:
    driver: bridge

volumes:
  certs:
  dist:
  db:
    driver: local
  pgadmin-data:
