export enum ResampleMethodEnum {
  DISTANCE_THRESHOLD = 'DISTANCE_THRESHOLD',
  RAMER_DOUGLAS_PEUCKER = 'RAMER_DOUGLAS_PEUCKER',
  VISVALINGAM_WHYATT_MB = 'VISVALINGAM_WHYATT_MB',
  VISVALINGAM_WHYATT_SBRL = 'VISVALINGAM_WHYATT_SBRL',
}
